<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE weapons [
        <!ELEMENT weapons (weapon)*>
        <!ELEMENT weapon (name, type, damage, rarity)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT damage (#PCDATA)>
        <!ELEMENT rarity (#PCDATA)>
        ]>

<weapons>
    <weapon>
        <name>Armagedon</name>
        <type>Epee</type>
        <damage>20</damage>
        <rarity>0.01</rarity>
    </weapon>
    <weapon>
        <name>Arc lance flamme</name>
        <type>Arc</type>
        <damage>7</damage>
        <rarity>0.3</rarity>
    </weapon>
    <weapon>
        <name>Acide sulfurique</name>
        <type>Poison</type>
        <damage>9</damage>
        <rarity>0.3</rarity>
    </weapon>
    <weapon>
        <name>Eau bouillante</name>
        <type>Poison</type>
        <damage>6</damage>
        <rarity>0.5</rarity>
    </weapon>
</weapons>